version: '3.2'
services:
  api-socks:
    build:
      dockerfile: './api/Dockerfile'
    image: api-socks:latest
    container_name: shop-api
    restart: always
    ports:
      - '3000:3000'
  ws-5-frontend:
    build:
      dockerfile: './ws-5/Dockerfile'
    image: node:lts
    container_name: shop-front
    restart: always
    ports:
      - '8080:8080'