version: '3.9'

services:
  back:
    build: ./api
    container_name: backend
    hostname: backend
    ports:
      - "3000:3000"
    networks:
      default:
        aliases:
          - backend

  front:
    build: ./ws-5
    container_name: frontend
    hostname: frontend
    ports:
      - "8080:8080"